In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# 外形
a.shape

(2, 3)

In [6]:
# 维度数量
a.ndim

2

In [7]:
# 元素总数
a.size

6

In [8]:
# 每一个元素所占内存大小（字节）
a.itemsize

8

In [9]:
# 数据类型
a.dtype

dtype('int64')

In [11]:
# 创建数组时指定类型
b = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int8)
b

array([[ 1,  2,  3],
       [ 4,  5, 44]], dtype=int8)

In [14]:
# 指定类型时，要注意此类型能够正确表达所需的数据
b = np.array([[1, 2, 3], [4, 5, 300]], dtype=np.int8)
b

array([[ 1,  2,  3],
       [ 4,  5, 44]], dtype=int8)

In [15]:
# np.int8不能表示超过127的数字，所以300就不是300了
300-256

44