In [1]:
import numpy as np

### 3.5.2 数组与数的运算

In [2]:
a = np.arange(3)
a

array([0, 1, 2])

In [3]:
a + 1

array([1, 2, 3])

In [4]:
a * 10

array([ 0, 10, 20])

### 3.5.3 数组与数组的运算

In [5]:
arr1 = np.array([[1, 2, 3, 2, 1, 4], [5, 6, 1, 2, 3, 1]])
arr2 = np.array([[1, 2, 3, 4], [3, 4, 5, 6]])

In [6]:
arr1.shape, arr2.shape

((2, 6), (2, 4))

In [8]:
# 形状不同，不能操作
# arr1 + arr2

### 3.5.4 广播机制

In [14]:
a = np.arange(6).reshape((2, 1, 3))
a.shape

(2, 1, 3)

In [11]:
b = np.arange(6).reshape((2, 3))
b.shape

(2, 3)

In [17]:
print(a + b)
(a + b).shape

[[[ 0  2  4]
  [ 3  5  7]]

 [[ 3  5  7]
  [ 6  8 10]]]


(2, 2, 3)

## 矩阵

In [21]:
a = np.array([[80, 86],
[82, 80],
[85, 78],
[90, 90],
[86, 82],
[82, 90],
[78, 80],
[92, 94]])
b = np.array([0.7, 0.3])

In [22]:
a.shape, b.shape

((8, 2), (2,))

In [24]:
scores = a * b
scores[:, 0] + scores[:, 1]

array([81.8, 81.4, 82.9, 90. , 84.8, 84.4, 78.6, 92.6])

In [25]:
# 手动计算综合分
scores1 = a[:, 0] * b[0]
scores2 = a[:, 1] * b[1]
scores1 + scores2

array([81.8, 81.4, 82.9, 90. , 84.8, 84.4, 78.6, 92.6])

In [26]:
a = np.array([[80, 86],
[82, 80],
[85, 78],
[90, 90],
[86, 82],
[82, 90],
[78, 80],
[92, 94]])
b = np.array([[0.7], [0.3]])

In [27]:
a.shape, b.shape

((8, 2), (2, 1))

In [28]:
a = np.mat(a)
b = np.mat(b)

In [29]:
a.shape, b.shape

((8, 2), (2, 1))

In [30]:
a * b

matrix([[81.8],
        [81.4],
        [82.9],
        [90. ],
        [84.8],
        [84.4],
        [78.6],
        [92.6]])

### 矩阵api

In [31]:
a = np.array([[80, 86],
[82, 80],
[85, 78],
[90, 90],
[86, 82],
[82, 90],
[78, 80],
[92, 94]])
b = np.array([[0.7], [0.3]])

In [33]:
# a和b不需要先转换成矩阵，只要两者的形状匹配即可
np.dot(a, b)

array([[81.8],
       [81.4],
       [82.9],
       [90. ],
       [84.8],
       [84.4],
       [78.6],
       [92.6]])