# pandas
### 为什么要用pandas?
- pandas对numpy, matplotlib进行封装
- 对数据更友好的显示
- 更快的对数据的操作
- 都是用numpy进行数据的计算, pandas进行数据的处理，　matploylib对数据进行图形化的处理

## 案列: 回忆我们在numpy中创建的股票的涨幅形式

In [6]:
import numpy as np
# 正态分布，　生成均值为０，标准差１的　　　　形态（１０，　５）
stock_change = np.random.normal(0, 1, (10, 5))
stock_change

array([[ 0.4977132 , -0.02615169, -0.27002746, -0.76072652,  1.74305386],
       [-1.58271944,  0.02163562,  0.20173155,  1.18238644, -0.11506464],
       [ 1.10341738, -1.42804039, -0.18444123, -0.07008924,  0.67561543],
       [ 0.67972909,  0.53284919,  0.38852405, -1.00685584, -1.71581229],
       [ 0.91106039,  1.94769984, -0.26205291, -0.02970188,  0.47989172],
       [-0.31803196, -0.3010128 , -1.26904722,  1.29740347, -0.76435609],
       [-1.87301167, -0.08455043, -1.02647736,  0.26479014,  0.52528018],
       [ 2.00387478,  0.60759514,  0.21326888, -0.68040583,  0.63355414],
       [-0.55912441, -0.37518771,  1.59790687,  0.74361315, -1.06470076],
       [ 0.95815305,  1.01307997,  0.55816445,  1.13294564,  2.11211814]])

In [25]:
# 转换成pandas形式　　　　DataFrame数据类型
import pandas as pd
stock_code = ['股票' + str(i) for i in range(10)]
stock_day_rise = pd.DataFrame(stock_change, index=stock_code)
# 显示出成表格形式
stock_day_rise

0         1         2         3         4
股票0  0.497713 -0.026152 -0.270027 -0.760727  1.743054
股票1 -1.582719  0.021636  0.201732  1.182386 -0.115065
股票2  1.103417 -1.428040 -0.184441 -0.070089  0.675615
股票3  0.679729  0.532849  0.388524 -1.006856 -1.715812
股票4  0.911060  1.947700 -0.262053 -0.029702  0.479892
股票5 -0.318032 -0.301013 -1.269047  1.297403 -0.764356
股票6 -1.873012 -0.084550 -1.026477  0.264790  0.525280
股票7  2.003875  0.607595  0.213269 -0.680406  0.633554
股票8 -0.559124 -0.375188  1.597907  0.743613 -1.064701
股票9  0.958153  1.013080  0.558164  1.132946  2.112118

In [30]:
# 增加行索引
stock_code = ['股票' + str(i) for i in range(10)]
stock_code
stock_day_rise.shape[0]
stock_day_rise
# 添加行索引
data = pd.DataFrame(stock_day_rise, index=stock_code)
data = pd.DataFrame(stock_day_rise, index=stock_code)
data

0   1   2   3   4
股票0 NaN NaN NaN NaN NaN
股票1 NaN NaN NaN NaN NaN
股票2 NaN NaN NaN NaN NaN
股票3 NaN NaN NaN NaN NaN
股票4 NaN NaN NaN NaN NaN
股票5 NaN NaN NaN NaN NaN
股票6 NaN NaN NaN NaN NaN
股票7 NaN NaN NaN NaN NaN
股票8 NaN NaN NaN NaN NaN
股票9 NaN NaN NaN NaN NaN

In [29]:
data

0   1   2   3   4
股票0 NaN NaN NaN NaN NaN
股票1 NaN NaN NaN NaN NaN
股票2 NaN NaN NaN NaN NaN
股票3 NaN NaN NaN NaN NaN
股票4 NaN NaN NaN NaN NaN
股票5 NaN NaN NaN NaN NaN
股票6 NaN NaN NaN NaN NaN
股票7 NaN NaN NaN NaN NaN
股票8 NaN NaN NaN NaN NaN
股票9 NaN NaN NaN NaN NaN

In [37]:
# 生成数据
stock_data = np.random.normal(size=(10, 5))
# 构建索引
index = ['股票' + str(i) for i in range(stock_data.shape[0])]
# 生成有有列表的表格数据
data1 = pd.DataFrame(stock_data, index=index)

In [38]:
data1

0         1         2         3         4
股票0 -1.702901  0.925913  0.071566 -1.182041  1.233194
股票1 -1.095020  0.987216 -0.501915  0.260007 -1.038902
股票2 -1.660335  0.014685 -0.174377  0.581658 -1.557958
股票3 -0.006692  1.477422  0.801805 -1.795572 -2.523386
股票4  0.320389 -0.778824  0.093143 -0.045424  0.664452
股票5 -1.925495  0.143330  1.133282  0.741712  1.333218
股票6  0.803548 -0.788776 -1.236342 -0.114000 -0.400642
股票7  0.521733 -0.662775 -0.268570 -0.569412 -1.049250
股票8 -0.702542 -0.389222  0.346350 -2.071526 -1.204020
股票9 -0.397324  0.327857 -0.387933  0.757978  0.449248

# 生成列索引
## pd.data_range(start, end, periods, freq)
- start 开始时间
- end 结束时间
- periods 时间天数
- freq 递进单位，　默认１天，　＇B' 默认跳过周末

In [41]:
# 构建行索引
date = pd.date_range('2017-01-01', periods=data1.shape[1], frep='B')
date

DatetimeIndex(['2017-01-01', '2017-01-02', '2017-01-03', '2017-01-04',
               '2017-01-05'],
              dtype='datetime64[ns]', freq='D')

In [43]:
# 生成列索引
data = pd.DataFrame(stock_data, index=index, columns=date)
data

2017-01-01  2017-01-02  2017-01-03  2017-01-04  2017-01-05
股票0   -1.702901    0.925913    0.071566   -1.182041    1.233194
股票1   -1.095020    0.987216   -0.501915    0.260007   -1.038902
股票2   -1.660335    0.014685   -0.174377    0.581658   -1.557958
股票3   -0.006692    1.477422    0.801805   -1.795572   -2.523386
股票4    0.320389   -0.778824    0.093143   -0.045424    0.664452
股票5   -1.925495    0.143330    1.133282    0.741712    1.333218
股票6    0.803548   -0.788776   -1.236342   -0.114000   -0.400642
股票7    0.521733   -0.662775   -0.268570   -0.569412   -1.049250
股票8   -0.702542   -0.389222    0.346350   -2.071526   -1.204020
股票9   -0.397324    0.327857   -0.387933    0.757978    0.449248

# DataFrame　结构
- 行索引 index 表明不同行，　横向索引，　０轴，　axis=0
- 列索引　colmuns 表明不同列，　１轴，　axis=1

# DataFrame 属性

- index

In [46]:
data.index

Index(['股票0', '股票1', '股票2', '股票3', '股票4', '股票5', '股票6', '股票7', '股票8', '股票9'], dtype='object')

- columns

In [47]:
data.columns

DatetimeIndex(['2017-01-01', '2017-01-02', '2017-01-03', '2017-01-04',
               '2017-01-05'],
              dtype='datetime64[ns]', freq='D')

- values

In [48]:
data.values

array([[-1.70290149,  0.92591314,  0.07156575, -1.18204054,  1.23319375],
       [-1.09502044,  0.98721636, -0.50191523,  0.26000695, -1.03890216],
       [-1.66033518,  0.01468518, -0.17437748,  0.58165824, -1.55795837],
       [-0.00669212,  1.47742153,  0.80180533, -1.79557183, -2.5233857 ],
       [ 0.32038856, -0.77882438,  0.09314309, -0.04542401,  0.66445196],
       [-1.9254953 ,  0.14332965,  1.13328202,  0.74171163,  1.33321825],
       [ 0.80354782, -0.78877588, -1.23634223, -0.11399961, -0.40064208],
       [ 0.52173298, -0.66277501, -0.26857005, -0.56941243, -1.04924964],
       [-0.7025424 , -0.38922234,  0.34634978, -2.07152637, -1.20401983],
       [-0.39732417,  0.32785695, -0.3879325 ,  0.75797766,  0.44924811]])

- .T

In [49]:
data.T

股票0       股票1       股票2       股票3       股票4       股票5  \
2017-01-01 -1.702901 -1.095020 -1.660335 -0.006692  0.320389 -1.925495   
2017-01-02  0.925913  0.987216  0.014685  1.477422 -0.778824  0.143330   
2017-01-03  0.071566 -0.501915 -0.174377  0.801805  0.093143  1.133282   
2017-01-04 -1.182041  0.260007  0.581658 -1.795572 -0.045424  0.741712   
2017-01-05  1.233194 -1.038902 -1.557958 -2.523386  0.664452  1.333218   

                 股票6       股票7       股票8       股票9  
2017-01-01  0.803548  0.521733 -0.702542 -0.397324  
2017-01-02 -0.788776 -0.662775 -0.389222  0.327857  
2017-01-03 -1.236342 -0.268570  0.346350 -0.387933  
2017-01-04 -0.114000 -0.569412 -2.071526  0.757978  
2017-01-05 -0.400642 -1.049250 -1.204020  0.449248

- head
- 显示头几行，　默认５行

In [50]:
data.head(3)

2017-01-01  2017-01-02  2017-01-03  2017-01-04  2017-01-05
股票0   -1.702901    0.925913    0.071566   -1.182041    1.233194
股票1   -1.095020    0.987216   -0.501915    0.260007   -1.038902
股票2   -1.660335    0.014685   -0.174377    0.581658   -1.557958

- tail
- 显示后几行，　默认５行

In [51]:
data.tail(3)

2017-01-01  2017-01-02  2017-01-03  2017-01-04  2017-01-05
股票7    0.521733   -0.662775   -0.268570   -0.569412   -1.049250
股票8   -0.702542   -0.389222    0.346350   -2.071526   -1.204020
股票9   -0.397324    0.327857   -0.387933    0.757978    0.449248

## 修改索引
- 不可以　一个一个的改，如：
- data.index[0] = '股票_0'  # 错误的
- 只能先把值全部改了，　然后重新设计索引

In [54]:
index[0] = '股票＿０'
data.index = index
data.index

Index(['股票＿０', '股票1', '股票2', '股票3', '股票4', '股票5', '股票6', '股票7', '股票8', '股票9'], dtype='object')

# 重设索引
- reset_index(drop=False)
    - 设置新的下标
    - drop:　默认为False，　不删除原来的索引，　如果为True, 删除原来的索引
    

In [57]:
# 不删除原来的索引
data.reset_index()

index  2017-01-01 00:00:00  2017-01-02 00:00:00  2017-01-03 00:00:00  \
0  股票＿０            -1.702901             0.925913             0.071566   
1   股票1            -1.095020             0.987216            -0.501915   
2   股票2            -1.660335             0.014685            -0.174377   
3   股票3            -0.006692             1.477422             0.801805   
4   股票4             0.320389            -0.778824             0.093143   
5   股票5            -1.925495             0.143330             1.133282   
6   股票6             0.803548            -0.788776            -1.236342   
7   股票7             0.521733            -0.662775            -0.268570   
8   股票8            -0.702542            -0.389222             0.346350   
9   股票9            -0.397324             0.327857            -0.387933   

   2017-01-04 00:00:00  2017-01-05 00:00:00  
0            -1.182041             1.233194  
1             0.260007            -1.038902  
2             0.581658            -1.557958  
3            -1.795572            -2.523386  
4            -0.045424             0.664452  
5             0.741712             1.333218  
6            -0.114000            -0.400642  
7            -0.569412            -1.049250  
8            -2.071526            -1.204020  
9             0.757978             0.449248

In [58]:
# 删除原来的索引
data.reset_index(drop=True)

2017-01-01  2017-01-02  2017-01-03  2017-01-04  2017-01-05
0   -1.702901    0.925913    0.071566   -1.182041    1.233194
1   -1.095020    0.987216   -0.501915    0.260007   -1.038902
2   -1.660335    0.014685   -0.174377    0.581658   -1.557958
3   -0.006692    1.477422    0.801805   -1.795572   -2.523386
4    0.320389   -0.778824    0.093143   -0.045424    0.664452
5   -1.925495    0.143330    1.133282    0.741712    1.333218
6    0.803548   -0.788776   -1.236342   -0.114000   -0.400642
7    0.521733   -0.662775   -0.268570   -0.569412   -1.049250
8   -0.702542   -0.389222    0.346350   -2.071526   -1.204020
9   -0.397324    0.327857   -0.387933    0.757978    0.449248

# 设置新索引案例

- 创建

In [59]:
df = pd.DataFrame({'month': [1, 4, 7, 10],
                    'year': [2012, 2014, 2013, 2014],
                    'sale':[55, 40, 84, 31]})
df

month  sale  year
0      1    55  2012
1      4    40  2014
2      7    84  2013
3     10    31  2014

- 以月份设置新的索引

In [62]:
df.set_index('month')

sale  year
month            
1        55  2012
4        40  2014
7        84  2013
10       31  2014

- 设置多个索引，以年和月份

In [63]:
df.set_index(['year', 'month'])

sale
year month      
2012 1        55
2014 4        40
2013 7        84
2014 10       31

- 通过上面的操作，　这样DataFrame 就成了一个具有MultiIndex的DataFrame
- 其实就是一个三维结构

In [67]:
print(df.index)
dn = df.set_index(['year', 'month'])
dn.index

RangeIndex(start=0, stop=4, step=1)


MultiIndex(levels=[[2012, 2013, 2014], [1, 4, 7, 10]],
           labels=[[0, 2, 1, 2], [0, 1, 2, 3]],
           names=['year', 'month'])

# MultiIndex
## index属性
- names: levels的名称
- levels: 每个level的元组值

In [70]:
dn.index.levels

FrozenList([[2012, 2013, 2014], [1, 4, 7, 10]])

In [72]:
dn.index.names

FrozenList(['year', 'month'])

In [73]:
dn.index.labels

FrozenList([[0, 2, 1, 2], [0, 1, 2, 3]])

# Series
## Series 是一个一维的数组结构　　和 python 中的字典很像　　　　

In [85]:
print(type(data.iloc[0]))
print(data.index)

<class 'pandas.core.series.Series'>
Index(['股票＿０', '股票1', '股票2', '股票3', '股票4', '股票5', '股票6', '股票7', '股票8', '股票9'], dtype='object')


## 创建Series

In [93]:
pd.Series(np.arange(10))

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [94]:
# 指定索引创建
pd.Series([1, 3, 4, 6], index=list('ABCD'))

A    1
B    3
C    4
D    6
dtype: int64

In [95]:
list('abcd')

['a', 'b', 'c', 'd']

### 通过字典来创建Seriese


In [98]:
aa = pd.Series({'aa': 11, 'bb': 22})

In [99]:
aa

aa    11
bb    22
dtype: int64

In [100]:
aa.index

Index(['aa', 'bb'], dtype='object')

In [101]:
aa.values

array([11, 22])

# 小结
- Seriese 是一维的数组
- DataFrame 是二维的数组
- MultiIndex 和　DataFrame 组合起来就是三维数组