In [1]:
%matplotlib inline

In [4]:
from __future__ import division
from numpy.random import randn
import numpy as np 
np.set_printoptions(precision=4, suppress=True)

In [5]:
data = randn(2, 3)

In [6]:
data

array([[-0.6964,  0.181 ,  0.1783],
       [ 0.7925,  1.1422,  0.374 ]])

In [7]:
data * 10

array([[-6.9644,  1.8101,  1.7834],
       [ 7.9252, 11.4219,  3.7404]])

In [8]:
data + data

array([[-1.3929,  0.362 ,  0.3567],
       [ 1.585 ,  2.2844,  0.7481]])

In [10]:
# 会自动转换类型
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [11]:
arr1.dtype

dtype('float64')

In [13]:
# 将列表嵌套列表的对象作为２位数组
data2 = [[1, 2, 3, 4],[5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)


In [14]:
arr2.dtype

dtype('int64')

In [15]:
# 其他函数快速创建一个数组
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
np.empty((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [18]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
# arange 和　range 一样 多了可以以小数为步长
np.arange(1, 15, 0.8)

array([ 1. ,  1.8,  2.6,  3.4,  4.2,  5. ,  5.8,  6.6,  7.4,  8.2,  9. ,
        9.8, 10.6, 11.4, 12.2, 13. , 13.8, 14.6])

In [25]:
# 指定类型属性来创建数组
arr = np.array([1, 2, 3, 5])

In [26]:
arr.dtype

dtype('int64')

In [27]:
arr.astype(np.int8)

array([1, 2, 3, 5], dtype=int8)

In [29]:
# 以小数形式转换成int类型的时候，会出现精度
a = np.array([1.065, -2.4312])
b = a.astype(np.int8)
b = b.astype(np.float64)

In [31]:
b.dtype

dtype('float64')

In [32]:
numeric_stings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [35]:
numeric_stings

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [36]:
numeric_stings.astype(np.float64)

array([ 1.25, -9.6 , 42.  ])

In [47]:
empty_unint32 = np.empty(8, dtype=np.uint32)

In [48]:
empty_unint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

# 数组和标量间的运算

In [51]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr
arr * arr
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [53]:
1/ arr
arr ** 0.5

array([[1.    , 1.4142, 1.7321],
       [2.    , 2.2361, 2.4495]])

## 基本的索引和切片

In [59]:
arr = np.arange(10)
arr
arr[5]
arr[5:8]
arr[5: 8] = 8
arr

array([0, 1, 2, 3, 4, 8, 8, 8, 8, 9])

In [65]:
#　等于号是原数据的映射，　如果需要独立的空间就需要copy()
arr_slice = arr[5: 8]
arr_slice[1] = 123154
print(arr) 
arr_slice[:] = 64
arr

[     0      1      2      3      4     64 123154     64      8      9]


array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [72]:
arr2d = np.arange(1, 10).reshape(3, 3)
arr2d[2]

array([7, 8, 9])

In [77]:
# 两种索引方式都是等价的
arr2d[0][2]
arr2d[0, 2]

3

In [87]:
arr3d = np.arange(1, 13).reshape(2, 2, 3)
print(arr3d)
arr3d[0]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


array([[1, 2, 3],
       [4, 5, 6]])

In [88]:
old_values = arr3d[0].copy()
arr3d[0] = 42
print(arr3d)
arr3d[0] = old_values
arr3d

[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [90]:
arr3d[1, 0]

array([7, 8, 9])

## 切片索引

In [95]:
arr[1: 6]

array([ 1,  2,  3,  4, 64])

In [98]:
arr2d
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [99]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [101]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [106]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

## 布尔型索引

In [116]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = randn(7, 4)
print(names)
data

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']


array([[-0.2182, -1.0919,  0.5284,  1.5169],
       [-1.5563,  0.8094,  1.1042, -2.1302],
       [-0.6182, -1.3527, -0.3865, -1.2611],
       [-0.2519,  0.413 ,  0.195 , -0.1047],
       [-0.4276,  0.9778,  0.2978, -1.3108],
       [-0.0907, -0.4295,  0.6428,  2.6106],
       [-0.1575,  0.0487, -0.4689,  0.1183]])

In [118]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [121]:
data[names == 'Bob']

array([[-0.2182, -1.0919,  0.5284,  1.5169],
       [-0.2519,  0.413 ,  0.195 , -0.1047]])

In [123]:
data[names == 'Bob', 2:]

array([[ 0.5284,  1.5169],
       [ 0.195 , -0.1047]])

In [125]:
data[names == 'Bob', 3]

array([ 1.5169, -0.1047])

In [128]:
make = (names == 'Bob') | (names == 'Will')
make

array([ True, False,  True,  True,  True, False, False])

In [131]:
data[make]

array([[-0.2182, -1.0919,  0.5284,  1.5169],
       [-0.6182, -1.3527, -0.3865, -1.2611],
       [-0.2519,  0.413 ,  0.195 , -0.1047],
       [-0.4276,  0.9778,  0.2978, -1.3108]])

In [134]:
data[data < 0] = 0

In [136]:
data

array([[0.    , 0.    , 0.5284, 1.5169],
       [0.    , 0.8094, 1.1042, 0.    ],
       [0.    , 0.    , 0.    , 0.    ],
       [0.    , 0.413 , 0.195 , 0.    ],
       [0.    , 0.9778, 0.2978, 0.    ],
       [0.    , 0.    , 0.6428, 2.6106],
       [0.    , 0.0487, 0.    , 0.1183]])

In [139]:
data[names != 'Joe'] = 7
data

array([[7.    , 7.    , 7.    , 7.    ],
       [0.    , 0.8094, 1.1042, 0.    ],
       [7.    , 7.    , 7.    , 7.    ],
       [7.    , 7.    , 7.    , 7.    ],
       [7.    , 7.    , 7.    , 7.    ],
       [0.    , 0.    , 0.6428, 2.6106],
       [0.    , 0.0487, 0.    , 0.1183]])

# 神奇索引
- 通过传入一个整数数组来进行索引，按照索引的顺序取出对应的元素

In [141]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [149]:
arr[[1, 3, 7, 0]]

array([[1., 1., 1., 1.],
       [3., 3., 3., 3.],
       [7., 7., 7., 7.],
       [0., 0., 0., 0.]])

In [151]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [156]:
arr = np.arange(32).reshape(8, 4)

In [159]:
# 根据两个整数数组－－对应直接选中元素，数组长度必须一致为n，　结果长度也为n
arr[[1, 5, 7, 2],[0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [161]:
# 在原来的数组上添加新的数组，　［［１，　５，　７，　２］］　
# 然后在从第一组的数组上的这个索引[:, [0, 3, 1, 2, 1, 3]]来返回新的数组
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2, 1, 3]]

array([[ 4,  7,  5,  6,  5,  7],
       [20, 23, 21, 22, 21, 23],
       [28, 31, 29, 30, 29, 31],
       [ 8, 11,  9, 10,  9, 11]])

In [163]:
# 和上面一样，　只是换了一种形式
arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [165]:
np.ix_?

# 数组转至和轴对换

In [169]:
arr = np.arange(15).reshape(3, 5)
print(arr)
arr.T

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [171]:
arr = np.random.randn(6, 3)
np.dot(arr, arr.T)

array([[ 7.6267,  0.477 , -2.3907, -0.5945,  0.9979, -2.0912],
       [ 0.477 ,  4.196 ,  0.1205,  1.0906,  1.7472, -1.3439],
       [-2.3907,  0.1205,  4.1801, -0.6103, -0.1559,  1.503 ],
       [-0.5945,  1.0906, -0.6103,  0.5732,  0.3661, -0.4014],
       [ 0.9979,  1.7472, -0.1559,  0.3661,  0.8126, -0.7513],
       [-2.0912, -1.3439,  1.503 , -0.4014, -0.7513,  1.1779]])

In [181]:
arr = np.arange(16).reshape(2, 2, 4)
print(arr)
arr.transpose(1, 0, 2)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [189]:
print(arr)
arr.swapaxes(1, 2)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

# 通用函数：快速的元素级别组的函数

In [197]:
arr = np.arange(10)
# np.sqrt(arr)　返回被平方的值
np.sqrt(arr)
np.exp(arr)

array([   1.    ,    2.7183,    7.3891,   20.0855,   54.5982,  148.4132,
        403.4288, 1096.6332, 2980.958 , 8103.0839])

In [203]:
7.3891 ** 0.2

1.491826470331665

In [205]:
x = randn(8)
y = randn(8)
print(x)
print(y)
#　np.maximum(x, y) 返回这两个元素的中的最大值
np.maximum(x, y)

[ 0.1885 -1.7026 -0.1013 -0.7152 -0.1517  0.1692 -0.5344  0.1851]
[-0.0768 -0.6852  0.1037  2.3065 -1.017  -0.9196 -1.0035 -0.1257]


array([ 0.1885, -0.6852,  0.1037,  2.3065, -0.1517,  0.1692, -0.5344,
        0.1851])

In [208]:
arr = randn(7) * 5
print(arr)
# np.modf  把整数和小数分开
np.modf(arr)

[13.3194  2.9198 12.1969 -5.1176  2.7166  1.892  -0.6105]


(array([ 0.3194,  0.9198,  0.1969, -0.1176,  0.7166,  0.892 , -0.6105]),
 array([13.,  2., 12., -5.,  2.,  1., -0.]))

In [217]:
a = np.arange(24).reshape(4, 2, 3)
b = np.arange(1, 25).reshape(4, 2, 3)
np.maximum(a, b)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

# 利用数组做数据分析
- 用数组表达式代替循环的做法称为矢量法，　运算速度要比使用循环快上一两个数量级别

In [227]:
points = np.arange(-5, 5, 1)
a = np.meshgrid(points, points)
a

[array([[-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4]]),
 array([[-5, -5, -5, -5, -5, -5, -5, -5, -5, -5],
        [-4, -4, -4, -4, -4, -4, -4, -4, -4, -4],
        [-3, -3, -3, -3, -3, -3, -3, -3, -3, -3],
        [-2, -2, -2, -2, -2, -2, -2, -2, -2, -2],
        [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
        [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
        [ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3],
        [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4]

In [225]:
ys

array([[-5, -5, -5, -5, -5, -5, -5, -5, -5, -5],
       [-4, -4, -4, -4, -4, -4, -4, -4, -4, -4],
       [-3, -3, -3, -3, -3, -3, -3, -3, -3, -3],
       [-2, -2, -2, -2, -2, -2, -2, -2, -2, -2],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3],
       [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4]])

In [223]:
np.meshgrid?